sudo: required
services:
  - docker

before_install:
  - docker build -t davycode/docker-react -f Dockerfile.dev .

script: 
  - docker run davycode/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "eu-west-2"  
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-447855631175"
  bucket_path: "docker-react"
  on: 
    branch: master